# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dev4devs-com/postgresql-operator

    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE=on
    steps:
    - checkout
    - run:
        name: Install operator-sdk to run make setup
        command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin
    - run: export GOPROXY=https://proxy.golang.org/
    - run: make setup
    - run: make code-build-linux
    - run: GO111MODULE=off go get github.com/mattn/goveralls
    - run: make test
    - run: make integration-cover
    - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=jFmmyeYiX3zI1sj2jDCsR1QYwIrL33Xij

  image_push_master:
    working_directory: /go/src/github.com/dev4devs-com/postgresql-operator
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE=on
    steps:
    - checkout
    - run:
        name: Install operator-sdk to run make setup
        command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin
    - run: export GOPROXY=https://proxy.golang.org/
    - run: make setup
    - run: make code-build-linux
    # circle ci key required for docker builds
    - setup_remote_docker
    - run: make image-build-master
    - run: make image-push-master

  image_release:
    working_directory: /go/src/github.com/dev4devs-com/postgresql-operator
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE=on
    steps:
    - checkout
    - run:
        name: Install operator-sdk to run make setup
        command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin
    - run: export GOPROXY=https://proxy.golang.org/
    - run: make setup
    - run: make code-build-linux
    # circle ci key required for docker builds
    - setup_remote_docker
    - run: make image-build-release
    - run: make image-push-release

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - image_push_master:
        requires:
        - build
        filters:
          branches:
            only:
            - master
    - image_release:
        requires:
        - build
        filters:
          tags:
            only: /\d{1,2}\.\d{1,2}\.\d{1,2}/
          branches:
            ignore: /.*/