apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.postgresql-operator.dev4devs.com
spec:
  group: postgresql-operator.dev4devs.com
  names:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resource'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            awsAccessKeyId:
              description: Key ID of AWS S3 storage. Required to create the Secret
                with the data to allow send the backup files to AWS S3 storage.
              type: string
            awsCredentialsSecretName:
              description: Name of the secret with the AWS data credentials already
                created in the cluster
              type: string
            awsCredentialsSecretNamespace:
              description: Name of the namespace where the scret with the AWS data
                credentials is in the cluster
              type: string
            awsS3BucketName:
              description: Name of AWS S3 storage. Required to create the Secret with
                the data to allow send the backup files to AWS S3 storage.
              type: string
            awsSecretAccessKey:
              description: Secret/Token of AWS S3 storage. Required to create the
                Secret with the data to allow send the backup files to AWS S3 storage.
              type: string
            databaseVersion:
              description: 'Database version. (E.g 9.6). IMPORTANT: Just the first
                2 digits should be used.'
              type: string
            encryptKeySecretName:
              description: Name of the secret with the EncryptKey data already created
                in the cluster
              type: string
            encryptKeySecretNamespace:
              description: Name of the namespace where the secret with the EncryptKey
                data is in the cluster
              type: string
            gpgEmail:
              description: 'GPG email to create the EncryptionKeySecret with this
                data See here how to create this key : https://help.github.com/en/articles/generating-a-new-gpg-key'
              type: string
            gpgPublicKey:
              description: 'GPG public key to create the EncryptionKeySecret with
                this data See here how to create this key : https://help.github.com/en/articles/generating-a-new-gpg-key'
              type: string
            gpgTrustModel:
              description: 'GPG trust model to create the EncryptionKeySecret with
                this data. the default value is true when it is empty. See here how
                to create this key : https://help.github.com/en/articles/generating-a-new-gpg-key'
              type: string
            image:
              description: 'Image:tag used to do the backup. More Info: https://github.com/integr8ly/backup-container-image'
              type: string
            postgresqlCRName:
              description: Name of the PostgreSQL CR applied which this backup will
                work with
              type: string
            productName:
              description: Used to create the directory where the files will be stored
              type: string
            schedule:
              description: 'Schedule period for the CronJob  "0 0 * * *" # daily at
                00:00.'
              type: string
          type: object
        status:
          properties:
            awsCredentialsSecretNamespace:
              description: Namespace  of the secret object with the Aws data to allow
                send the backup files to the AWS storage
              type: string
            awsSecretData:
              additionalProperties:
                type: string
              description: Data  of the secret object with the Aws data to allow send
                the backup files to the AWS storage
              type: object
            awsSecretName:
              description: Name  of the secret object with the Aws data to allow send
                the backup files to the AWS storage
              type: string
            backupStatus:
              description: Will be as "OK when all objects are created successfully
              type: string
            cronJobName:
              description: Name of the CronJob object created and managed by it to
                schedule the backup job
              type: string
            cronJobStatus:
              description: Status of the CronJob object
              type: object
            databasePodFound:
              description: Boolean value which has true when the Database Pod was
                found in order to create the secret with the database data to allow
                the backup image connect into it.
              type: boolean
            databaseServiceFound:
              description: Boolean value which has true when the Service Database
                Pod was found in order to create the secret with the database data
                to allow the backup image connect into it.
              type: boolean
            dbSecretData:
              additionalProperties:
                type: string
              description: Data  of the secret object created with the database data
                to allow the backup image connect to the database
              type: object
            dbSecretName:
              description: Name of the secret object created with the database data
                to allow the backup image connect to the database
              type: string
            encryptionKeySecretData:
              additionalProperties:
                type: string
              description: Data of the secret object with the Encryption GPG Key
              type: object
            encryptionKeySecretName:
              description: Name  of the secret object with the Encryption GPG Key
              type: string
            encryptionKeySecretNamespace:
              description: Namespace of the secret object with the Encryption GPG
                Key
              type: string
            hasEncryptionKey:
              description: Boolean value which has true when it has an EncryptionKey
                to be used to send the backup files
              type: boolean
          required:
          - backupStatus
          - cronJobName
          - dbSecretName
          - dbSecretData
          - awsSecretName
          - awsSecretData
          - awsCredentialsSecretNamespace
          - encryptionKeySecretName
          - encryptionKeySecretNamespace
          - encryptionKeySecretData
          - hasEncryptionKey
          - databasePodFound
          - databaseServiceFound
          - cronJobStatus
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
